### ISSUE TITLE
Correct value for jdbc.dbver property

### ISSUE THREAD

**Issue by VladyslavKurmaz** [Papka24/base#7]
What should be correct value for jdbc.dbver?
If I try to use default value: 5, I receive next error.
```
jdbc.dbver: 5
170627-20:28:05.059 [u.p.s.d.u.UpgradeUtil:133] error upgrade database:
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:92)
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
        at ua.papka24.server.db.util.UpgradeUtil.upgrade(UpgradeUtil.java:84)
        at ua.papka24.server.Main.main(Main.java:179)
```

**Comment by MaximBelov** [comment]
You can leave dbver empty
jdbc.dbver= 

____

ERROR: relation "users" does not exist

Replace in file server/src/main/resources/sql/CreateDB.sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO papka24_ro;
with
GRANT SELECT ON ALL TABLES IN SCHEMA public TO papka24;

Import from CreateDB.sql

**Comment by VladyslavKurmaz** [comment]
Thanks!
This issue is resoved now and can be closed.
